Change portal coordinate system and adjust yaw
GTNewHorizons/PersonalSpace pull request #4
Opened 2022-08-03 16:51 UTC by vlaetansky

1. Use target tile coordinates instead of target teleport coordinates
2. Properly calculate yaw so player always expect to spawn looking at the portal
3. Replace target portal if missing (closes GTNewHorizons/GT-New-Horizons-Modpack#10855)

2022-08-05 03:42 UTC, eigenraven commented
This introduces a way to duplicate PS portal blocks if you have access to any other interdimensional teleportation method. Breaking the return portal -> tp to overworld -> use portal -> you now have an overworld return portal that will work from any dimension for cheap overworld transport. Not spawning portals when it's missing on the other side is intentional for this reason.

2022-08-05 07:33 UTC, vlaetansky commented
> This introduces a way to duplicate PS portal blocks if you have access to any other interdimensional teleportation method. Breaking the return portal -> tp to overworld -> use portal -> you now have an overworld return portal that will work from any dimension for cheap overworld transport. Not spawning portals when it's missing on the other side is intentional for this reason.

well the same thing you can do with vanilla portals, not spawning portals is also not a good solution because of linked PR.

2022-08-05 07:36 UTC, vlaetansky commented
Possible solution is add a couple of limitations on where you can put active portals, so restrict portals with dimension ID to that very ID.

2022-08-13 20:38 UTC, eigenraven requested changes
Can you:
 - remove portal respawning
 - move getTargetDimension it to a private helper method in the Teleporter class (make the constructor accept the dimension id rather than WorldServer), it's server-side only but it's not obvious from its name

2022-08-16 12:48 UTC, eigenraven approved these changes

2022-08-16 12:48 UTC, merged